### ISSUE TITLE
Switching active watchface

### ISSUE THREAD

**Issue by jxors** [pebble/libpebble2#17]
Is there a way to switch the active watchface using this library?

When switching to a different watchface on my Pebble, the active watchface is not updated so every time I open a menu, the "wrong" watchface will show up.

**Comment by a-andreyev** [comment]
What firmware / watch model are you using?

**Comment by jxors** [comment]
I'm using a classic (aplite, kickstarter edition) Pebble running the newest firmware.

It seems like this has something to do with resetting the BlobDB for apps. (I'm sending a BlobDB clear, and then installing a few apps). Normal functionality is restored once I pair & connect it with my phone again.

**Comment by jxors** [comment]
Alright, I figured it out. I was parsing the app UUIDs using the wrong endianness. Swapping the right bytes around fixed this issue.

**Comment by Katharine** [comment]
What were you parsing UUIDs from that had the wrong endianness?

**Comment by jxors** [comment]
I'm parsing the UUID directly from the appinfo.json, using a C# application. Microsoft's implementation of UUIDs (GUIDs), for some reason, parses the first half of the string using the "wrong" endianness.

**Comment by brookpatten** [comment]
There's an implementation of UUIDs we've used successfully  from pebblesharp here: https://github.com/Keboo/PebbleSharp/blob/master/PebbleSharp.Core/UUID.cs
