### ISSUE TITLE
Serial Transport on Ubuntu?

### ISSUE THREAD

**Issue by mqchau** [pebble/libpebble2#4]
Can you please try pinging Pebble from Ubuntu directly via bluetooth serial connection? I'm having trouble with that. Much appreciated.

**Comment by Katharine** [comment]
I believe it should work if you follow steps like http://askubuntu.com/a/252235, except give `/dev/rfcomm0` to libpebble2 instead of screen.

I don't have an Ubuntu machine handy to try it, though.

**Comment by mqchau** [comment]
Thanks. I'll try that.

**Comment by mqchau** [comment]
So that instruction works on Debian but not Ubuntu. Well, that was close enough I guess.
