### ISSUE TITLE
Model number for Pebble Time Steel not listed

### ISSUE THREAD

**Issue by jameswilddev** [pebble/libpebble2#5]
The table of models/colors in https://github.com/pebble/libpebble2/blob/master/libpebble2/protocol/system.py doesn't seem to include any for the Pebble Time Steel.  If I'm reading the response payload correctly I get a value of 15/0x0F when querying my gunmetal black Pebble Time Steel.

**Comment by Katharine** [comment]
Added them in 43c7d399e2d1ae4b6abdeaacb92a8249af94db81.

**Comment by jameswilddev** [comment]
Awesome, thank you!

**Comment by RobertMe** [comment]
Could it be that the hardware names/codes for the Time Steel are also missing, in: https://github.com/pebble/libpebble2/blob/master/libpebble2/util/hardware.py ? I think at least 10/0x0A is a valid value for those?

**Comment by Katharine** [comment]
You are correct; 10 is the (only) expected value for Pebble Time Steel.
